// ======================================================================
// \title  FlightLogicTesterHelpers.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for FlightLogic component test harness helper functions
// ======================================================================

#include "FlightLogicTester.hpp"

namespace Components {

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void FlightLogicTester ::
    connectPorts()
  {
    // Connect special input ports

    this->connect_to_cmdIn(
      0,
      this->component.get_cmdIn_InputPort(0)
    );

    // Connect special output ports

    this->component.set_cmdRegOut_OutputPort(
      0,
      this->get_from_cmdRegOut(0)
    );

    this->component.set_cmdResponseOut_OutputPort(
      0,
      this->get_from_cmdResponseOut(0)
    );

    this->component.set_logOut_OutputPort(
      0,
      this->get_from_logOut(0)
    );

    this->component.set_logTextOut_OutputPort(
      0,
      this->get_from_logTextOut(0)
    );

    this->component.set_timeCaller_OutputPort(
      0,
      this->get_from_timeCaller(0)
    );

    this->component.set_tlmOut_OutputPort(
      0,
      this->get_from_tlmOut(0)
    );

    // Connect typed input ports

    this->connect_to_dataRequest(
      0,
      this->component.get_dataRequest_InputPort(0)
    );

    this->connect_to_pingIn(
      0,
      this->component.get_pingIn_InputPort(0)
    );

    this->connect_to_recvTransmission(
      0,
      this->component.get_recvTransmission_InputPort(0)
    );

    this->connect_to_sendBeaconState(
      0,
      this->component.get_sendBeaconState_InputPort(0)
    );

    this->connect_to_startup(
      0,
      this->component.get_startup_InputPort(0)
    );

    // Connect typed output ports

    this->component.set_deployAntenna_OutputPort(
      0,
      this->get_from_deployAntenna(0)
    );

    this->component.set_deployCamera_OutputPort(
      0,
      this->get_from_deployCamera(0)
    );

    this->component.set_epsHealth_OutputPort(
      0,
      this->get_from_epsHealth(0)
    );

    this->component.set_fakeData_OutputPort(
      0,
      this->get_from_fakeData(0)
    );

    this->component.set_pingOut_OutputPort(
      0,
      this->get_from_pingOut(0)
    );

    this->component.set_sendTrans_OutputPort(
      0,
      this->get_from_sendTrans(0)
    );

    this->component.set_takePic_OutputPort(
      0,
      this->get_from_takePic(0)
    );
  }

  void FlightLogicTester ::
    initComponents()
  {
    this->init();
    this->component.init(FlightLogicTester::TEST_INSTANCE_QUEUE_DEPTH, FlightLogicTester::TEST_INSTANCE_ID);
  }

}
